CREATE DATABASE db;
USE db;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    pword VARCHAR(255) NOT NULL
);

CREATE TABLE locations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL
);

SHOW DATABASES;
SHOW TABLES;

DESCRIBE users;
DESCRIBE locations;

SELECT * FROM users;
SELECT * FROM locations;

TRUNCATE TABLE locations;
TRUNCATE TABLE users;

